### ISSUE TITLE
Events on dashboard are displayed wrong

### ISSUE THREAD

**Issue by Cyborgmatt** [klausman/sat_exporter#1]
Thank you for putting together an exporter for SAT. Do you have any advice on how to show the actual event numbers on the dashboard?

Currently, it is displaying like this:

![image](https://github.com/klausman/sat_exporter/assets/3114217/57437362-efc9-4eb5-a5a5-2f9537b853b4)

The warning symbol in the corner shows the following:

"PromQL info: metric might not be a counter, name does not end in _total/_sum/_count/_bucket: "reforger_sat_exporter_events" (1:6)"

Thanks

**Comment by klausman** [comment]
So the warning is caused by the metric name is `reforger_sat_exporter_events`, and Grafan tries to guess this is not a counter and so warns about it. I can probably rename the metric to `reforger_sat_exporter_events_total` to shut that up. 

The dashboard shows how often these events happen per second (which is the default for stuff like this), hence the really low floating-point number. You'd not expect "player joined" to happen several times a second all the time, obviously. You can sortof fake this as "per minute" by adding `*60` at the end of the query, i.e. `rate(reforger_sat_exporter_events{server=~"$server"}[5m])*60)`, but that is sortof faking what is really happening. Another thing to play with is the `5m` time window. In this case it calculates the number of events happening in the last 45m. Depending on how often you scrape the exporter, much lower values like 30s can be used. That will make the graph more "spiky", but be closer to what is actually going on.

If you just want a perpetually increasing line (like Uptime), just drop the rate call and time window, i.e. `reforger_sat_exporter_events{server=~"$server"}`.
